language: node_js

env:
- ASCIIDOCTOR_CORE_VERSION=v1.5.5
- ASCIIDOCTOR_CORE_VERSION=master

node_js:
- node

jdk:
- oraclejdk8

script:
- ./build.sh

sudo: false

before_deploy:
- >
  if ! [ "$BEFORE_DEPLOY_RUN" ]; then
    export BEFORE_DEPLOY_RUN=1;
    npm run dist;
    mkdir bin
    cd dist/;
    zip -r ../bin/asciidoctor.js.dist.zip .;
    tar -zcvf ../bin/asciidoctor.js.dist.tar.gz .;
    cd ..;
  fi

deploy:
- provider: releases
  api_key: ${GITHUB_TOKEN}
  file: /bin/asciidoctor.js.dist.*
  skip_cleanup: true
  file_glob: true
  on:
    repo: ldez/ajsdeploy
    tags: true
    node: node
